[versions]
android-gradle-plugin = "8.9.0"
androidx-activity = "1.10.1"
androidx-compose-bom = "2025.02.00" # https://developer.android.com/jetpack/compose/bom/bom-mapping
androidx-lifecycle = "2.8.7"
kotest = "5.9.1"
kotlin = "2.1.10"
kotlinx-coroutines = "1.10.1"
mikepenz-aboutlibraries = "11.6.3"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = "androidx.appcompat:appcompat:1.7.0"
androidx-browser = "androidx.browser:browser:1.8.0"
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-core-ktx = "androidx.core:core-ktx:1.15.0"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.1.3"
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.8.8"
androidx-startup-runtime = "androidx.startup:startup-runtime:1.2.0"
compose-gradle-plugin = { module = "org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin", version.ref = "kotlin" }
facebook-stetho = "com.facebook.stetho:stetho:1.6.0"
jakewharton-timber = "com.jakewharton.timber:timber:5.0.1"
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
kotlinx-collections-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.8"
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.0"
mikepenz-aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "mikepenz-aboutlibraries" }
mockk = "io.mockk:mockk:1.13.17"
slack-compose-lint-checks = "com.slack.lint.compose:compose-lint-checks:1.4.2"

[bundles]
androidx-compose = [
    "androidx-compose-runtime",
    "androidx-compose-ui",
    "androidx-compose-ui-tooling-preview",
]

[plugins]
adarshr-test-logger = "com.adarshr.test-logger:4.0.0"
ben-manes-versions = "com.github.ben-manes.versions:0.52.0"
kotlinter = "org.jmailen.kotlinter:5.0.1"
triplet-play = "com.github.triplet.play:3.12.1"
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "mikepenz-aboutlibraries" }
