[versions]
android-gradle-plugin = "7.3.0"
androidx-activity = "1.5.1"
androidx-compose = "1.2.1"
androidx-compose-compiler = "1.3.1"
androidx-lifecycle = "2.5.1"
androidx-room = "2.4.2"
google-accompanist = "0.25.1"
google-hilt = "2.43.2"
kotest = "5.4.2"
kotlin = "1.7.10"
kotlinx-coroutines = "1.6.4"
mikepenz-aboutlibraries = "10.4.0"
mockk = "1.12.8"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-appcompat = "androidx.appcompat:appcompat:1.5.1"
androidx-browser = "androidx.browser:browser:1.4.0"
androidx-compose-material3 = "androidx.compose.material3:material3:1.0.0-beta02"
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose" }
androidx-core-ktx = "androidx.core:core-ktx:1.9.0"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"
androidx-hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.0.0"
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.5.2"
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-startup-runtime = "androidx.startup:startup-runtime:1.1.1"
facebook-stetho = "com.facebook.stetho:stetho:1.6.0"
google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "google-accompanist" }
google-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "google-hilt" }
google-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "google-hilt" }
google-hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "google-hilt" }
jakewharton-timber = "com.jakewharton.timber:timber:5.0.1"
javax-inject = "javax.inject:javax.inject:1"
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-api-jvm = { module = "io.kotest:kotest-framework-api-jvm", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-collections-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.5"
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
mikepenz-aboutlibraries-compose = { module = "com.mikepenz:aboutlibraries-compose", version.ref = "mikepenz-aboutlibraries" }
mikepenz-aboutlibraries-gradle-plugin = { module = "com.mikepenz.aboutlibraries.plugin:aboutlibraries-plugin", version.ref = "mikepenz-aboutlibraries" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-agent-jvm = { module = "io.mockk:mockk-agent-jvm", version.ref = "mockk" } # See https://github.com/mockk/mockk/issues/605
square-javapoet = "com.squareup:javapoet:1.13.0"
square-moshi = "com.squareup.moshi:moshi:1.13.0"

[bundles]
androidx-compose = [
    "androidx-compose-runtime",
    "androidx-compose-material3",
    "androidx-compose-ui",
    "androidx-compose-ui-tooling-preview",
]

[plugins]
ben-manes-versions = "com.github.ben-manes.versions:0.42.0"
triplet-play = "com.github.triplet.play:3.7.0"
adarshr-test-logger = "com.adarshr.test-logger:3.2.0"
